### ISSUE TITLE
Demos Not Working in iOS9.1 iPhone6

### ISSUE THREAD

**Issue by shmdhussain** [jaridmargolin/bouncefix.js#10]
Demos are not working i.e both with and without fix works like same, fix is not working

**Comment by jaridmargolin** [comment]
I was just able to test, and the demos are working as expected.

The undesired behavior is sometimes difficult to reproduce. Adding a static header and differing background colors may help. I could also include a short gif in the README to illustrate what bouncefix accomplishes.
